# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'uRides' do
pod 'Stripe'
pod 'PaymentKit'
pod 'IQKeyboardManagerSwift'
pod 'Firebase'
end

target 'uRidesTests' do

end

target 'uRidesUITests' do

end

